# 4.1 Exercise on Functions:

# TASK1

In [5]:
# Length Conversion Function
def convert_length(value, from_unit, to_unit):

    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084  # 1 meter = 3.28084 feet
    elif from_unit == 'ft' and to_unit == 'm':
        return value * 0.3048   # 1 foot = 0.3048 meters
    else:
        raise ValueError("Only m↔ft conversions supported")
print(convert_length(5, 'm', 'ft'))
print(convert_length(10, 'ft', 'm'))



16.4042
3.048


In [7]:
#Weight Conversion Function
def convert_weight(value, from_unit, to_unit):
    """
    Converts weight between kilograms (kg) and pounds (lbs).
    """
    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462  # 1 kg = 2.20462 lbs
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value * 0.453592 # 1 lb = 0.453592 kg
    else:
        raise ValueError("Only kg↔lbs conversions supported")
print(convert_weight(2.5, 'kg', 'lbs'))
print(convert_weight(10, 'lbs', 'kg'))


5.51155
4.53592


In [8]:
#Volume Conversion Function
def convert_volume(value, from_unit, to_unit):
    """
    Converts volume between liters (L) and gallons (gal).
    """
    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172  # 1 L = 0.264172 gal
    elif from_unit == 'gal' and to_unit == 'L':
        return value * 3.78541   # 1 gal = 3.78541 L
    else:
        raise ValueError("Only L↔gal conversions supported")
print(convert_volume(5, 'L', 'gal'))
print(convert_volume(10, 'gal', 'L'))

1.3208600000000001
37.8541


In [9]:
#Main Menu Function
def show_menu():
    print("Unit Conversion Menu:")
    print("1. Length Conversion")
    print("2. Weight Conversion")
    print("3. Volume Conversion")
def get_user_choice():
  try:
    choice = input("Enter the number of the conversion you want to perform: ")
    if choice not in ['1','2','3']:
        raise ValueError("Invalid choice. Please enter a number between 1 and 3.")
    return choice
  except ValueError as e:
    print(e)
    return None

In [ ]:
#Input Value Function
def get_user_value():
    try:
        value = float(input("Enter value to convert: "))
        return value
    except ValueError:
        print("Error: Please enter a valid number")
        return None

In [10]:
#Length Input Handler
def handle_length(value):
    print("Options: m→ft or ft→m")
    from_unit = input("From (m/ft): ").strip().lower()
    to_unit = input("To (ft/m): ").strip().lower()

    try:
        result = convert_length(value, from_unit, to_unit)
        print(f"{value} {from_unit} = {result:.4f} {to_unit}")
    except ValueError as e:
        print(f"Error: {e}")

In [14]:
def main():
    show_menu()

    choice = get_user_choice()
    if choice is None:
        return

    value = get_user_value()
    if value is None:
        return

    if choice == '1':
        handle_length(value)
    elif choice == '2':
        print("Options: kg→lbs or lbs→kg")  # Similar pattern
        # Add weight handler here
    elif choice == '3':
        print("Options: L→gal or gal→L")    # Similar pattern
        # Add volume handler here

if __name__ == "__main__":
    main()


Unit Conversion Menu:
1. Length Conversion
2. Weight Conversion
3. Volume Conversion


KeyboardInterrupt: Interrupted by user

TASK 2


In [15]:
#Sum function
def calculate_sum(numbers):

    if not numbers:
        raise ValueError("Cannot calculate sum of empty list")
    return sum(numbers)

# Test it:
print(calculate_sum([1, 2, 3, 4, 5]))
print(calculate_sum([10.5, 20.3]))

15
30.8


In [16]:
#Average function
def calculate_average(numbers):
    if not numbers:
        raise ValueError("Cannot calculate average of empty list")
        return sum(numbers) / len(numbers)
print(calculate_average([1, 2, 3, 4, 5]))
print(calculate_average([10, 20, 30]))

None
None


In [19]:
#Maximum function
def find_max(numbers):
    if not numbers:
        raise ValueError("Cannot find maximum of empty list")
    return max(numbers)

# Test it:
print(find_max([1, 5, 3, 9, 2]))
print(find_max([10.5, 2.1, 8.7]))

9
10.5


In [18]:
#Minimum Function
def find_minimum(numbers):
    if not numbers:
        raise ValueError("Cannot find minimum of empty list")
    return min(numbers)

# Test it:
print(find_minimum([1, 5, 3, 9, 2]))
print(find_minimum([10.5, 2.1, 8.7]))


1
2.1


In [20]:
#Get Numbers Input Function
def get_numbers_from_input():

    user_input = input("Enter numbers separated by spaces: ").strip()
    if not user_input:
        raise ValueError("No numbers provided")

    try:
        numbers = [float(x) for x in user_input.split()]
        return numbers
    except ValueError:
        raise ValueError("All inputs must be valid numbers")


In [21]:
#Menu Function
def show_menu():
    print("=== Math Operations on List ===")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    print("-" * 20)

def get_user_choice():
    try:
        choice = input("Select operation (1-4): ").strip()
        if choice not in ['1', '2', '3', '4']:
            raise ValueError("Please select 1, 2, 3, or 4")
        return choice
    except ValueError as e:
        print(f"Error: {e}")
        return None


In [22]:
# Main Function Structure
def main():
    show_menu()

    choice = get_user_choice()
    if choice is None:
        return

    try:
        numbers = get_numbers_from_input()

        if choice == '1':
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"Average: {result:.4f}")
        elif choice == '3':
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == '4':
            result = find_minimum(numbers)
            print(f"Minimum: {result}")

    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()


=== Math Operations on List ===
1. Sum
2. Average
3. Maximum
4. Minimum
--------------------
Select operation (1-4): 4
Enter numbers separated by spaces: 1
Minimum: 1.0


# 4.2 Excercise on List Manipulation

#Extract Every Other Element

In [24]:
#Extract Every Other Element
def extract_every_other(lst):

    return lst[::2]
print(extract_every_other([1, 2, 3, 4, 5, 6]))
print(extract_every_other(['a', 'b', 'c', 'd']))


[1, 3, 5]
['a', 'c']


In [26]:
#Slice a Sublist
def get_sublist(lst, start, end):

    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))
print(get_sublist(['a', 'b', 'c', 'd', 'e'], 1, 3))


[3, 4, 5]
['b', 'c', 'd']


In [27]:
#Reverse a List Using Slicing python
def reverse_list(lst):
    return lst[::-1]
print(reverse_list([1, 2, 3, 4, 5]))
print(reverse_list(['a', 'b', 'c']))

[5, 4, 3, 2, 1]
['c', 'b', 'a']


In [28]:
# Remove First and Last Elements
def remove_first_last(lst):
   return lst[1:-1]
print(remove_first_last([1, 2, 3, 4, 5]))
print(remove_first_last(['a', 'b', 'c', 'd']))

[2, 3, 4]
['b', 'c']


In [30]:
#Get First n Elements
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))
print(get_first_n(['a', 'b', 'c', 'd'], 2))


[1, 2, 3]
['a', 'b']


In [31]:
#Get Last n Elements
def get_last_n(lst, n):
  return lst[-n:]
print(get_last_n([1, 2, 3, 4, 5], 2))
print(get_last_n(['a', 'b', 'c', 'd'], 3))

[4, 5]
['b', 'c', 'd']


In [32]:
#Reverse Skip (Every Second from End)
def reverse_skip(lst):
  return lst[-2::-2]

# Test it:
print(reverse_skip([1, 2, 3, 4, 5, 6]))
print(reverse_skip([7, 8, 9, 10, 11]))

[5, 3, 1]
[10, 8]


# 4.3 Exercise on Nested List:

In [33]:
#Flatten a Nested List
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result
print(flatten([[1, 2], [3, 4], [5]]))


[1, 2, 3, 4, 5]


In [35]:
# Access Nested List Element
def access_nested_element(lst, indices):
    current = lst
    for i in indices:
        current = current[i]
    return current

nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(nested, [1, 2]))


6


In [36]:
#Sum All Elements in Nested List
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Test it:
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21


21


In [37]:
#Remove Specific Element
def remove_element(lst, elem):

    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    return lst

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


In [40]:
#Find Maximum in Nested List
def find_max(lst):
    if not lst:
        raise ValueError("Cannot find maximum of empty list")

    max_val = float('-inf') # Initialize with negative infinity

    for item in lst:
        if isinstance(item, list):
            current_max = find_max(item)
        else:
            current_max = item

        if current_max > max_val:
            max_val = current_max

    return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))


6


In [42]:
#Count Occurrences
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))


3


In [43]:
#Deep Flatten
def deep_flatten(lst):

    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))


[1, 2, 3, 4, 5, 6, 7, 8]


In [45]:
#Nested List Average
def average_nested(lst):

    total = sum_nested(lst)
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_elements(item)
        else:
            count += 1
    return total / count

def count_elements(lst):

    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_elements(item)
        else:
            count += 1
    return count

print(average_nested([[1, 2], [3, 4], [5, 6]]))


3.5


# 10.1 Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [46]:
import numpy as np
print("NumPy imported successfully!")


NumPy imported successfully!


In [47]:
# Initialize empty array 2x2
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_2x2)
print(f"Shape: {empty_2x2.shape}")

1. Empty 2x2 array:
[[2.01518133e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
Shape: (2, 2)


In [48]:
# Initialize all ones array 4x2
ones_4x2 = np.ones((4, 2))
print("\n2. All ones 4x2 array:")
print(ones_4x2)
print(f"Shape: {ones_4x2.shape}")



2. All ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (4, 2)


In [49]:
# Create array filled with specific value
full_array = np.full((3, 3), 42)
print("\n3. Array filled with 42 (3x3):")
print(full_array)
print(f"Shape: {full_array.shape}")

# Another example
full_custom = np.full((2, 4), 7.5)
print("\nCustom fill 7.5 (2x4):")
print(full_custom)


3. Array filled with 42 (3x3):
[[42 42 42]
 [42 42 42]
 [42 42 42]]
Shape: (3, 3)

Custom fill 7.5 (2x4):
[[7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5]]


In [50]:
# Given array
original = np.array([[1, 2], [3, 4]])

# Zeros with same shape/type
zeros_like = np.zeros_like(original)
print("\n4. Zeros like original array:")
print("Original:")
print(original)
print("Zeros like:")
print(zeros_like)
print(f"Shape: {zeros_like.shape}")


4. Zeros like original array:
Original:
[[1 2]
 [3 4]]
Zeros like:
[[0 0]
 [0 0]]
Shape: (2, 2)


In [51]:
# Given array
original = np.array([[1, 2, 3], [4, 5, 6]])

# Ones with same shape/type
ones_like = np.ones_like(original)
print("\n5. Ones like original array:")
print("Original:")
print(original)
print("Ones like:")
print(ones_like)
print(f"Shape: {ones_like.shape}")


5. Ones like original array:
Original:
[[1 2 3]
 [4 5 6]]
Ones like:
[[1 1 1]
 [1 1 1]]
Shape: (2, 3)


In [52]:
# Existing Python list
new_list = [1, 2, 3, 4]

# Convert to NumPy array
np_array = np.array(new_list)
print("\n6. List to NumPy array:")
print("Original list:", new_list)
print("NumPy array:", np_array)
print("Type:", type(np_array))
print("Array type:", np_array.dtype)


6. List to NumPy array:
Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Array type: int64


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [53]:
# Create array from 10 to 49
arr_range = np.arange(10, 50)
print("1. Range 10-49:")
print(arr_range)
print(f"Shape: {arr_range.shape}, Length: {len(arr_range)}")

1. Range 10-49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,), Length: 40


In [54]:
# Create 3x3 matrix with values 0-8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):")
print(matrix_3x3)


2. 3x3 matrix (0-8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
# Create identity matrix
identity = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(identity)


3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
# Random array size 30, find mean
random_30 = np.random.random(30)
mean_val = random_30.mean()
print("\n4. Random array (30) + mean:")
print(f"Array: {random_30[:5]}...")  # First 5 elements
print(f"Mean: {mean_val:.4f}")


4. Random array (30) + mean:
Array: [0.17895621 0.71475488 0.17857518 0.4930995  0.01911384]...
Mean: 0.4577


In [57]:
# 10x10 random array, find min/max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n5. 10x10 random array:")
print(f"Min: {min_val:.4f}, Max: {max_val:.4f}")
print("Array shape:", random_10x10.shape)


5. 10x10 random array:
Min: 0.0074, Max: 0.9859
Array shape: (10, 10)


In [58]:
# Zero array size 10, replace 5th (index 4)
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (0-based index)
print("\n6. Zero array with 5th element = 1:")
print(zero_arr)


6. Zero array with 5th element = 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [59]:
# Reverse given array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reverse array:")
print("Original:", arr)
print("Reversed: ", reversed_arr)


7. Reverse array:
Original: [1 2 0 0 4 0]
Reversed:  [0 4 0 0 2 1]


In [60]:
# 2D array: 1s on border, 0s inside (5x5 example)
size = 5
border_arr = np.zeros((size, size))
border_arr[0, :] = 1      # Top border
border_arr[-1, :] = 1     # Bottom border
border_arr[:, 0] = 1      # Left border
border_arr[:, -1] = 1     # Right border
print("\n8. Border 1s, inside 0s:")
print(border_arr)


8. Border 1s, inside 0s:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
# 8x8 checkerboard
checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1      # Even rows, even cols
checkerboard[1::2, 1::2] = 1    # Odd rows, odd cols
print("\n9. 8x8 Checkerboard:")
print(checkerboard)


9. 8x8 Checkerboard:
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# PROBLEM 3: Array Operations

In [62]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("Given arrays:")
print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)

Given arrays:
x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]


In [63]:
result = x + y
print("1. x + y:")
print(result)

1. x + y:
[[ 6  8]
 [10 13]]


In [64]:
result = x - y
print("2. x - y:")
print(result)

2. x - y:
[[-4 -4]
 [-4 -3]]


In [65]:
result = x * 3
print("3. x * 3:")
print(result)

3. x * 3:
[[ 3  6]
 [ 9 15]]


In [66]:
result = x ** 2
print("4. Square of x:")
print(result)

4. Square of x:
[[ 1  4]
 [ 9 25]]


In [67]:
print("5. Dot products:")
print("v · w =", np.dot(v, w))
print("x · v =", np.dot(x, v))
print("x · y =\n", np.dot(x, y))

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]


In [68]:
print("6. Concatenate:")
# Row-wise (vertical)
row_concat = np.vstack((x, y))
print("x || y (row-wise):\n", row_concat)

# Column-wise (horizontal)
col_concat = np.hstack((v, w))
print("v || w (column-wise):", col_concat)

6. Concatenate:
x || y (row-wise):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v || w (column-wise): [ 9 10 11 12]


In [69]:
print("7. x || v (SHOULD FAIL):")
try:
    np.concatenate((x, v))  # ERROR: Different dimensions!
except ValueError as e:
    print("ERROR:", e)
print("Why? x is 2x2 matrix, v is 1D array → incompatible shapes")

7. x || v (SHOULD FAIL):
ERROR: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Why? x is 2x2 matrix, v is 1D array → incompatible shapes


# PROBLEM 4: Matrix Operations

In [70]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print("A:\n", A)
print("B:\n", B)

A:
 [[3 4]
 [7 8]]
B:
 [[5 3]
 [2 1]]


In [71]:
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("4.1 A·A⁻¹:")
print("Result (should be identity):\n", identity)
print("Is identity?", np.allclose(identity, np.eye(2)))

4.1 A·A⁻¹:
Result (should be identity):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is identity? True


In [72]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("4.2 Matrix Multiplication:")
print("AB =\n", AB)
print("BA =\n", BA)
print("AB ≠ BA?", not np.array_equal(AB, BA))

4.2 Matrix Multiplication:
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB ≠ BA? True


In [73]:
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("4.3 Transpose property:")
print("(AB)ᵀ =\n", AB_T)
print("BᵀAᵀ =\n", BT_AT)
print("Equal?", np.allclose(AB_T, BT_AT))

4.3 Transpose property:
(AB)ᵀ =
 [[23 51]
 [13 29]]
BᵀAᵀ =
 [[23 51]
 [13 29]]
Equal? True


# 4.4 Solve Linear System AX = B

In [74]:
# Matrix form: A * X = B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])

# Method 1: Solve directly
X = np.linalg.solve(A, B)
print("4.4 Linear system solution:")
print("X =", X)
print("x =", X[0], "y =", X[1], "z =", X[2])

# Method 2: Using inverse
X_inv = np.dot(np.linalg.inv(A), B)
print("Using inverse:", X_inv)

4.4 Linear system solution:
X = [ 2.  1. -2.]
x = 2.0 y = 1.0000000000000002 z = -2.0
Using inverse: [ 2.  1. -2.]
